RESPUESTAS_OK = {
    1: "OK",
    2: "De acuerdo",
    3: "Confirmo",
    4: "Recibido",
    5: "Enterado",
    6: "Listo",
    7: "¡Listo!",
    8: "¡Perfecto!",
    9: "¡Hecho!",
    10: "¡Va!",
    11: "¡Claro!",
    12: "¡Todo bien!",
    13: "¡Activado!",
    14: "¡Vamos!",
    15: "¡Dale!",
    16: "¡Se arma!",
    17: "¡Ya quedó!",
    18: "¡A disfrutar!",
}
